eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.86:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: collection-retry-service
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  file: ./${spring.application.name}.log
