eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.86:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: collection-aisdeploy-app

email:
  to: pgf@aishk.com

allow:
  from: sztest1@aishk.com
logging:
  file: ./${spring.application.name}.log
  level:
    com.peak.collection.aisdeploy.controller.service: debug
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
svnlog:
  path: /home/ais74/script/temp/svn_%s.log
