server:
  port: 8761
spring:
  application:
    name: collection-eureka-server
eureka:
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://192.168.1.201:${server.port}/eureka/,http://192.168.1.203:${server.port}/eureka/,http://192.168.1.207:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://192.168.1.86:${server.port}/eureka/
logging:
  file: ./${spring.application.name}.log